#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const child_process = require('child_process');
const packager = require('electron-packager');
const filesize = require('filesize');
const packageJson = require('../package.json');

const name = packageJson.name;
const version = packageJson.version;
const root = path.join.bind(path, path.resolve(__dirname, '..'));

const options = {
  dir: root(),
  out: root('releases'),
  appVersion: version,
  name: name,
  appCopyright: 'Copyright 2017 blinksocks',
  platform: 'linux,win32,darwin',
  arch: 'ia32,x64',
  asar: true,
  packageManager: 'yarn',
  overwrite: true,
  prune: true,
  quiet: false,
  win32metadata: {
    CompanyName: '',
    FileDescription: 'Cross-platform desktop GUI for blinksocks',
    OriginalFilename: name,
    ProductName: name,
    InternalName: name
  },
  // If the file extension is omitted, it is auto-completed to the correct extension based on the platform
  // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon
  icon: path.resolve(__dirname, '..', 'resources', 'icon')
};

const execFileSync = function (sh, args = []) {
  if (typeof sh === 'string') {
    return child_process.execFileSync(sh, args, {cwd: root('releases')});
  }
};

packager(options, function done(err, appPaths) {
  if (err) {
    console.error(err);
  } else {
    const targzFiles = [/* {name, hash, size}, ... */];
    let isPatchGenerated = false;

    // post-process to each generated dir
    for (const dir of appPaths) {
      const newDir = `${dir}-v${version}`;
      try {
        // 1. append version
        fs.renameSync(dir, newDir);

        // 2. generate patch
        if (!isPatchGenerated) {
          let appAsar;
          if (newDir.indexOf('darwin') !== -1) {
            appAsar = path.join(newDir, `${name}.app/Contents/Resources/app.asar`);
          } else {
            appAsar = path.join(newDir, 'resources', 'app.asar');
          }
          execFileSync(root('tasks', 'create-patch.sh'), [appAsar, `${name}-v${version}.patch`]);
          const sha256 = execFileSync(root('tasks', 'sha256sum.sh'), [`${name}-v${version}.patch.gz`]);
          fs.appendFileSync(root('releases', 'sha256sum.txt'), sha256);
          isPatchGenerated = true;
        }

        const fname = path.basename(newDir);
        const fnameWithExt = `${fname}.tar.gz`;
        const fullFilePath = `${newDir}.tar.gz`;

        // 3. compress into .tar.gz
        execFileSync(root('tasks', 'compress.sh'), [fname, fullFilePath]);

        // 4. append hash to sha256sum.txt
        const stdout = execFileSync(root('tasks', 'sha256sum.sh'), [fnameWithExt]);
        const sha256 = stdout.toString().split(' ')[1].trim();
        fs.appendFileSync(root('releases', 'sha256sum.txt'), stdout);

        targzFiles.push({
          name: fnameWithExt,
          hash: sha256,
          size: fs.lstatSync(fullFilePath).size
        });
      } catch (err) {
        console.error(err);
        process.exit(1);
      }
    }

    // generate RELEASE.md
    targzFiles.sort((a, b) => a.name < b.name);
    const dlItems = targzFiles.map(({name, hash, size}) => `| [${name}] | ${hash} | ${filesize(size, {exponent: 2})} |`);
    const dlLinks = targzFiles.map(({name}) => `[${name}]: https://github.com/blinksocks/blinksocks-desktop/releases/download/v${version}/${name}`);
    const markdown = `[//]: # (THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.)

# Release

| NAME | SHA256 | SIZE |
| :--- | :----- | :--- |
${dlItems.join('\n')}

Looking for old versions? Please visit [releases](https://github.com/blinksocks/blinksocks-desktop/releases).

${dlLinks.join('\n')}
`;
    fs.writeFileSync(root('RELEASE.md'), markdown);
  }
});
